Hip88
helium/helium-foundation-k8s pull request #114
Opened 2023-07-12 05:28 UTC by mikev

Create a silver table consisting of gateway rewards.  This will allow a fast determination of "active" gateways.

Also create a silver table of packets.  Not needed for HIP88, but lets add this now.

2023-07-12 17:38 UTC, ChewingGlass requested changes

2023-07-12 17:38 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/hip88-silver.yaml
> +      FROM packet_router_packet_report_v1
I think we want a more generally usable packet router packet report silver table. We'll do the select distinct in another query that is unioned with PoC data

2023-07-12 18:17 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/hip88-silver.yaml
> +      FROM packet_router_packet_report_v1
Removed file

2023-07-13 19:21 UTC, ChewingGlass requested changes

2023-07-13 19:21 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/helium/iot-rewards-share-delta-lake-sink.yaml
> +            image: public.ecr.aws/k0m1p4t7/protobuf-delta-lake-sink:0.0.9
Needs to be 0.0.10

2023-07-13 19:21 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/helium/iot-rewards-share-delta-lake-sink.yaml
> +              - received_timestamp
Timestamp is wrong, and missing the timestamp divisor field. See helium-data scripts.

2023-07-13 19:21 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/helium/iot-rewards-share-delta-lake-sink.yaml
> +              - service/poc_lora.proto
I don't think this is the right proto. see the helium-data script

2023-07-13 19:22 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +      FROM iot_reward_share
If we're only taking gateway_reward, recommend (1) exploding this out by selecting the individual values and (2) filtering where gateway_reward is not null

2023-07-13 19:22 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      rssi,
unit

2023-07-13 19:22 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      frequency,
unit

2023-07-13 19:22 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      snr,
unit. And make sure it's matching the other silver table for these units

2023-07-13 19:23 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      payload_hash,
all bytes should be base64 encoded strings, as in the other silver table

2023-07-13 19:24 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      TABLE_LORA_POC_V1: s3a://foundation-data-lake-requester-pays/bronze/packet_router_packet_report_v1
Env var should be `TABLE_PACKET_ROUTER_PACKET_REPORT_V1` if that's how you want it to be named in your select statement

2023-07-13 19:24 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +      TABLE_LORA_POC_V1: s3a://foundation-data-lake-requester-pays/bronze/lora_poc_v1
fix env var name

2023-07-13 19:24 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +      CHECKPOINT: s3a://foundation-data-lake-requester-pays/checkpoints/iot-poc-silver
fix checkpoint location

2023-07-13 19:24 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +      OUTPUT: s3a://foundation-data-lake-requester-pays/silver/iot-poc-witnesses
fix output

2023-07-13 19:25 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +    instances: 3
This is a smaller table. Can we get away with fewer instances?

2023-07-13 21:01 UTC, mikev commented on manifests/poc-data-cluster/prod/helium/iot-rewards-share-delta-lake-sink.yaml
> +            image: public.ecr.aws/k0m1p4t7/protobuf-delta-lake-sink:0.0.9
Fixed

2023-07-13 21:02 UTC, mikev commented on manifests/poc-data-cluster/prod/helium/iot-rewards-share-delta-lake-sink.yaml
> +              - received_timestamp
Fixed

2023-07-13 21:52 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +    instances: 3
Reduced to 2

2023-07-13 21:53 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-rewards-silver.yaml
> +      OUTPUT: s3a://foundation-data-lake-requester-pays/silver/iot-poc-witnesses
Renamed to TABLE_IOT_PACKETS.
A simpler name is better.  Nobody know what "packet reports v1" means.

2023-07-13 21:56 UTC, mikev commented on manifests/poc-data-cluster/prod/helium/iot-rewards-share-delta-lake-sink.yaml
> +              - service/poc_lora.proto
What is wrong here?

2023-07-13 21:57 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      rssi,
Fixed.

2023-07-13 21:57 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      frequency,
Fixed.

2023-07-13 21:57 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      snr,
Fixed

2023-07-13 21:57 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-packets-silver.yaml
> +      payload_hash,
Fixed

2023-07-20 13:22 UTC, ChewingGlass approved these changes

2023-07-20 14:00 UTC, deasydoesit approved these changes
lgtm

2023-07-20 19:34 UTC, merged