create mobile job
helium/helium-foundation-k8s pull request #121
Opened 2023-07-21 21:42 UTC by mikev

Create a MOBILE job to create the bronze/mobile_reward_share table

2023-07-24 13:59 UTC, ChewingGlass requested changes

2023-07-24 13:59 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-region-counts-silver.yaml
> +    FROM TABLE_IOT_PACKETS GROUP BY region ORDER BY region DESC
This table name is wrong

2023-07-24 13:59 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-payload-totals-silver.yaml
> +    FROM TABLE_IOT_PACKETS
Have you tested these? I don't think you can do an aggregate in spark streaming without a window

2023-07-24 19:02 UTC, ChewingGlass requested changes

2023-07-24 19:02 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-data-reward-totals-silver.yaml
> +      date, sum(dc_transfer_amount_iot) AS data-iot-total
prefer underscores in sql column names

2023-07-27 17:30 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-region-counts-silver.yaml
> +    FROM TABLE_IOT_PACKETS GROUP BY region ORDER BY region DESC
Fixed

2023-07-27 17:45 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-data-reward-totals-silver.yaml
> +      date, sum(dc_transfer_amount_iot) AS data-iot-total
Fixed.

2023-07-27 17:50 UTC, mikev commented on manifests/poc-data-cluster/prod/spark/iot-payload-totals-silver.yaml
> +    FROM TABLE_IOT_PACKETS
It does not need to be an aggregate over a 24-hour period.  The count(region) could be over whatever time period the job chooses.  However the job windows do need to be non-overlapping.  How can we guarantee non-overlapping windows?

2026-07-15 19:09 UTC, closed without merging