Scheduled spark app updates
helium/helium-foundation-k8s pull request #193
Opened 2023-09-20 14:44 UTC by deasydoesit

2023-09-20 14:45 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/iot-hotspot-rewards-silver.yaml
> +  # Run 15 minutes after iot-reward-share-delta-lake-sink
Running after the proper k8s cron?

2023-09-20 14:46 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/iot-hotspot-rewards-silver.yaml
> +  schedule: "25 */4 * * *"
Running after the proper k8s cron?

2023-09-20 14:46 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/iot-hotspot-rewards-silver.yaml
> +    mainApplicationFile: "s3a://foundation-data-lake-requester-pays/jars/spark-streaming-sql-assembly-1.0.2.jar"
Update the jar version

2023-09-20 14:46 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/iot-hotspot-rewards-silver.yaml
> +        TRIGGER: AvailableNow
Added to align with `iot-packets-silver` but not sure if needed

2023-09-20 14:50 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/iot-poc-silver.yaml
Updated to align with the others but we'll be commenting out on Friday

2023-09-20 14:51 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/mobile-hotspot-rewards-silver.yaml
> +  schedule: "25 */4 * * *"
Running after the proper k8s cron?

2023-09-20 14:53 UTC, deasydoesit commented on manifests/poc-data-cluster/prod/spark/recently-rewarded-hotspots-gold.yaml
This job was already a `ScheduledSparkApplication`. 

I updated the `spark-streaming-sql-assembly` and added the `TRIGGER` env var, but not sure if needed or not

2023-09-20 14:55 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-hotspot-rewards-silver.yaml
> +  schedule: "25 */4 * * *"
Yep

2023-09-20 14:56 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/iot-hotspot-rewards-silver.yaml
> +        TRIGGER: AvailableNow
Yeah that's the only change needed

2023-09-20 14:57 UTC, ChewingGlass commented on manifests/poc-data-cluster/prod/spark/recently-rewarded-hotspots-gold.yaml
This one shouldn't be needed since BATCH_PROCESSING is true

2023-09-20 14:57 UTC, ChewingGlass requested changes
Don't need trigger on the gold table since BATCH_PROCESSING is true

2023-09-21 13:52 UTC, ChewingGlass approved these changes

2023-09-22 13:44 UTC, merged